server:
  port: 8000

logging:
  level:
    org.springframework: DEBUG
    org.hibernate:
      SQL: DEBUG

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb # in-memory
    username: sa
    password:
    driver-class-name: org.h2.Driver
  security:
    user:
      name: devhoon
      password: devhoon
  messages:
    basename: messages
  jpa:
    show-sql: true
# HAL EXPLORER 추가 기능설정
management:
  endpoints:
    web:
      exposure:
        include: "*"
