server:
  port: 8000

logging:
  level:
    org.springframework: DEBUG
    org.hibernate:
      SQL: DEBUG

spring:
  security:
    user:
      name: devhoon
      password: devhoon
  messages:
    basename: messages

management:
  endpoints:
    web:
      exposure:
        include: "*"
